#!/usr/bin/env bash
set -euo pipefail

# deploy-consumers.sh — Auto-discover and update ALL consumer repos
#
# Usage:
#   ./scripts/deploy-consumers.sh              # Dry run (validate only)
#   ./scripts/deploy-consumers.sh --push       # Regenerate + commit + push
#   ./scripts/deploy-consumers.sh --tier standard  # Use specific tier (default: minimal)
#
# Auto-discovers repos by scanning ~/Projects for .github/workflows/quality.yml
# files that contain the WORKFLOW_MODE marker from qa-architect.

PROJECTS_DIR="$HOME/Projects"
QA_ARCHITECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PUSH=false
TIER="minimal"
VERBOSE=false

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --push) PUSH=true; shift ;;
    --tier) TIER="$2"; shift 2 ;;
    --verbose) VERBOSE=true; shift ;;
    --help|-h)
      echo "Usage: deploy-consumers.sh [--push] [--tier minimal|standard|comprehensive] [--verbose]"
      echo ""
      echo "  --push     Commit and push changes (default: dry run)"
      echo "  --tier     Workflow tier to apply (default: minimal)"
      echo "  --verbose  Show detailed output"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

echo "=== QA Architect Consumer Deployment ==="
echo "Mode: $([ "$PUSH" = true ] && echo "PUSH (will commit + push)" || echo "DRY RUN (validate only)")"
echo "Tier: $TIER"
echo ""

# Discover consumer repos: any repo with quality.yml containing WORKFLOW_MODE marker
# Excludes qa-architect itself
CONSUMERS=()
for workflow in "$PROJECTS_DIR"/*/".github/workflows/quality.yml"; do
  [ -f "$workflow" ] || continue
  repo_dir="$(dirname "$(dirname "$(dirname "$workflow")")")"
  repo_name="$(basename "$repo_dir")"

  # Skip qa-architect itself (compare basenames to avoid case/symlink issues)
  [ "$(basename "$repo_dir")" = "$(basename "$QA_ARCHITECT_DIR")" ] && continue

  # Check for WORKFLOW_MODE marker (proves it was generated by qa-architect)
  if grep -q "WORKFLOW_MODE:" "$workflow" 2>/dev/null; then
    CONSUMERS+=("$repo_dir")
  fi
done

echo "Discovered ${#CONSUMERS[@]} consumer repos:"
for dir in "${CONSUMERS[@]}"; do
  echo "  - $(basename "$dir")"
done
echo ""

# Validation counters
PASS=0
FAIL=0
SKIPPED=0

for repo_dir in "${CONSUMERS[@]}"; do
  repo_name="$(basename "$repo_dir")"
  echo "--- $repo_name ---"

  # Check if repo has package.json (needed for npx)
  if [ ! -f "$repo_dir/package.json" ]; then
    echo "  SKIP: No package.json"
    SKIPPED=$((SKIPPED + 1))
    echo ""
    continue
  fi

  # Detect the existing tier from the workflow
  existing_tier="$TIER"
  if grep -q "WORKFLOW_MODE: standard" "$repo_dir/.github/workflows/quality.yml" 2>/dev/null; then
    existing_tier="standard"
  elif grep -q "WORKFLOW_MODE: comprehensive" "$repo_dir/.github/workflows/quality.yml" 2>/dev/null; then
    existing_tier="comprehensive"
  elif grep -q "WORKFLOW_MODE: minimal" "$repo_dir/.github/workflows/quality.yml" 2>/dev/null; then
    existing_tier="minimal"
  fi

  # Regenerate workflow (must cd to consumer dir — setup.js uses process.cwd())
  echo "  Regenerating workflow (tier: $existing_tier)..."
  if (cd "$repo_dir" && QAA_DEVELOPER=true node "$QA_ARCHITECT_DIR/setup.js" --update "--workflow-${existing_tier}" \
    2>&1 | { [ "$VERBOSE" = true ] && cat || tail -1; }); then
    :
  else
    echo "  FAIL: Workflow generation failed"
    FAIL=$((FAIL + 1))
    echo ""
    continue
  fi

  workflow_file="$repo_dir/.github/workflows/quality.yml"

  # Validate: no node_modules/create-qa-architect references
  if grep -q "node_modules/create-qa-architect" "$workflow_file"; then
    echo "  FAIL: Contains node_modules/create-qa-architect references"
    FAIL=$((FAIL + 1))
    echo ""
    continue
  fi

  # Validate: no section markers leaked
  if grep -qE '\{\{(QA_ARCHITECT_ONLY|FULL_DETECTION|FULL_REPORT)_(BEGIN|END)\}\}' "$workflow_file"; then
    echo "  FAIL: Contains section markers"
    FAIL=$((FAIL + 1))
    echo ""
    continue
  fi

  # Validate: valid YAML (requires node + js-yaml)
  if ! node -e "require('$QA_ARCHITECT_DIR/node_modules/js-yaml').load(require('fs').readFileSync('$workflow_file','utf8'))" 2>/dev/null; then
    echo "  FAIL: Invalid YAML"
    FAIL=$((FAIL + 1))
    echo ""
    continue
  fi

  # Remove stale devDep if present
  if grep -q '"create-qa-architect"' "$repo_dir/package.json" 2>/dev/null; then
    echo "  Removing stale create-qa-architect devDependency..."
    if [ "$PUSH" = true ]; then
      (cd "$repo_dir" && npm uninstall create-qa-architect 2>/dev/null || true)
    else
      echo "  (dry run - would remove devDep)"
    fi
  fi

  echo "  PASS: Validated"
  PASS=$((PASS + 1))

  # Commit and push if --push
  if [ "$PUSH" = true ]; then
    (
      cd "$repo_dir"
      if git diff --quiet .github/workflows/quality.yml package.json 2>/dev/null; then
        echo "  No changes to commit"
      else
        git add .github/workflows/quality.yml package.json package-lock.json 2>/dev/null || true
        git commit -m "chore: regenerate qa-architect workflow (${existing_tier} tier)

Fixes node_modules/create-qa-architect fallback paths.
Consumers use npx create-qa-architect@latest instead of devDep." 2>/dev/null || true
        git push 2>/dev/null && echo "  Pushed" || echo "  Push failed (check remote)"
      fi
    )
  fi

  echo ""
done

echo "=== Summary ==="
echo "  Pass: $PASS"
echo "  Fail: $FAIL"
echo "  Skipped: $SKIPPED"
echo "  Total: ${#CONSUMERS[@]}"

if [ "$FAIL" -gt 0 ]; then
  echo ""
  echo "Some repos failed validation. Review output above."
  exit 1
fi
